iverilog \
cpu_tb.v \
../cpu/cpu.v \
../modules/32bit-complementer/complementer.v \
../modules/32bit-Int-Alu/alu.v \
../modules/32bit-Int-controller/controller.v \
../modules/32bit-Int-Mul/mul.v \
../modules/32bit-regfile/reg_file.v \
../modules/branch-jump-controller/Branch_jump_controller.v \
../modules/data-cache/dcache_customable.v \
../modules/data-cache/dmem_customable.v \
../modules/data-load-controller/Data_load_controller.v \
../modules/data-store-controller/Data_store_controller.v \
../modules/i-cache/icache_customable.v \
../modules/i-cache/imem_customable.v \
../modules/LCD/hex2_char.v \
../modules/LCD/lcd_controller.v \
../modules/LCD/lcd_display.v \
../modules/mux/mux2x1.v \
../modules/mux/mux4x1.v \
../modules/mux/mux5x1.v \
../modules/pipeline/EX.v \
../modules/pipeline/ID.v \
../modules/pipeline/IF.v \
../modules/pipeline/MEM.v \
../modules/Test/test_lcd.v \
../modules/wire-module/Wire_module.v \
../modules/units/instruction_decode_unit.v \
../modules/units/instruction_execute_unit.v \
../modules/units/instruction_fetch_unit.v \
../modules/units/memory_access_unit.v \
-o cpu-tb.out
vvp cpu-tb.out